### ISSUE TITLE
Environment

### ISSUE THREAD

**Issue by pablo-moreno-uy** [pablo-moreno-uy/pablomoreno.uy#22]
ID: UH019

### Epic History:
- [ ] #20 

### User History:
Como stakeholder, quiero probar la web de manera online

### Tasks:
- [ ] Montar el server
- [x] Configurar el server
- [x] Montar el domino
- [x] Montar la API
- [ ] Configurar la API en la web 
- [ ] Subir web
- [ ] Probar 

### Criterios de Aceptación:
- [ ] Tasks
