### ISSUE TITLE
Detail

### ISSUE THREAD

**Issue by pablo-moreno-uy** [pablo-moreno-uy/pablomoreno.uy#9]
### Epic History:
- [ ] #1

### User History:
Como user, quiero ver las páginas de Detalle.

### Tasks:
- [ ] Routes
- [ ] Proyects Detail Page
- [ ] Services Detail Page
- [ ] Knowledge Detail Page

### Criterios de Aceptación:
 - [ ] Tasks
